# Generated by Django 5.2 on 2025-04-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanalytics',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
    ]
