# Generated by Django 5.2 on 2025-04-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
    ]
